import { Request, Response } from 'express';
import { promises as fs } from 'fs';
import { exec } from 'child_process';
import { promisify } from 'util';
import { RouteServer } from '../models';
import { IRouteServer } from '../models/routeServer.model';
import config from '../config/environment';
import { logAudit } from '../services/audit.service';

const execAsync = promisify(exec);

export const listRouteServers = async (_req: Request, res: Response): Promise<void> => {
  try {
    const rs = await RouteServer.find().sort({ order: 1, name: 1 }).lean();
    res.json({ success: true, data: rs });
  } catch (error) {
    res.status(500).json({ success: false, error: 'Failed to load route servers.' });
  }
};

export const createRouteServer = async (req: Request, res: Response): Promise<void> => {
  try {
    if (!req.body.name || !req.body.apiUrl) {
      res.status(400).json({ success: false, error: 'Name and API URL are required.' });
      return;
    }
    const rs = await RouteServer.create(req.body);
    await logAudit({ actor: req.user?.email, action: 'routeserver.create', resource: 'RouteServer', resourceId: String(rs._id), after: { name: rs.name } });
    res.status(201).json({ success: true, data: rs });
  } catch (error) {
    res.status(500).json({ success: false, error: 'Failed to create route server.' });
  }
};

export const updateRouteServer = async (req: Request, res: Response): Promise<void> => {
  try {
    const rs = await RouteServer.findByIdAndUpdate(req.params.id, req.body, { new: true });
    if (!rs) {
      res.status(404).json({ success: false, error: 'Route server not found.' });
      return;
    }
    await logAudit({ actor: req.user?.email, action: 'routeserver.update', resource: 'RouteServer', resourceId: String(rs._id) });
    res.json({ success: true, data: rs });
  } catch (error) {
    res.status(500).json({ success: false, error: 'Failed to update route server.' });
  }
};

export const deleteRouteServer = async (req: Request, res: Response): Promise<void> => {
  try {
    await RouteServer.findByIdAndDelete(req.params.id);
    await logAudit({ actor: req.user?.email, action: 'routeserver.delete', resource: 'RouteServer', resourceId: String(req.params.id) });
    res.json({ success: true });
  } catch (error) {
    res.status(500).json({ success: false, error: 'Failed to delete route server.' });
  }
};

/** Build the Alice-LG [[sources]] TOML from enabled route servers. */
const generateAliceConfig = (servers: IRouteServer[]): string => {
  const header = `# ─────────────────────────────────────────────────────────────
# alice.conf — [[sources]] generated by the MX-IX admin panel
# Merge these blocks into your alice.conf (or replace the sources section).
# ─────────────────────────────────────────────────────────────
`;
  const blocks = servers
    .filter((s) => s.enabled)
    .map((s, i) => {
      if (s.backend === 'gobgp') {
        return `[[sources]]
name = "${s.name}"
group = "${s.group || s.location || 'Route Servers'}"
[sources.gobgp]
grpc = "${s.apiUrl}"
processing_timeout = 300
`;
      }
      return `[[sources]]
name = "${s.name}"
group = "${s.group || s.location || 'Route Servers'}"
[sources.birdwatcher]
type = "${s.birdwatcherType || 'multi_table'}"
api = "${s.apiUrl}"
timezone = "UTC"
servertime_short = "2006-01-02 15:04:05"
servertime_ext = "2006-01-02 15:04:05 MST"
show_last_reboot = true
${i === 0 ? '' : ''}`;
    });
  return header + '\n' + blocks.join('\n');
};

/**
 * GET /api/admin/route-servers/config — preview the generated alice.conf sources.
 */
export const previewConfig = async (_req: Request, res: Response): Promise<void> => {
  try {
    const servers = await RouteServer.find({ enabled: true }).sort({ order: 1, name: 1 });
    const conf = generateAliceConfig(servers);
    res.json({
      success: true,
      data: {
        config: conf,
        applyConfigured: !!(config.aliceConfigPath && config.aliceReloadCmd),
        path: config.aliceConfigPath || null,
      },
    });
  } catch (error) {
    res.status(500).json({ success: false, error: 'Failed to generate config.' });
  }
};

/**
 * POST /api/admin/route-servers/apply — write alice.conf + reload (Option A).
 * Only works when ALICE_CONFIG_PATH + ALICE_RELOAD_CMD are set (backend has
 * host access). Otherwise returns the config for manual deployment.
 */
export const applyConfig = async (req: Request, res: Response): Promise<void> => {
  try {
    const servers = await RouteServer.find({ enabled: true }).sort({ order: 1, name: 1 });
    const conf = generateAliceConfig(servers);

    if (!config.aliceConfigPath || !config.aliceReloadCmd) {
      res.json({
        success: false,
        error: 'Apply is not configured. Set ALICE_CONFIG_PATH and ALICE_RELOAD_CMD on the backend host, or copy the generated config manually.',
        data: { config: conf },
      });
      return;
    }

    // Backup existing, write new, reload.
    try {
      const existing = await fs.readFile(config.aliceConfigPath, 'utf-8').catch(() => '');
      if (existing) await fs.writeFile(`${config.aliceConfigPath}.bak`, existing, 'utf-8');
    } catch {
      /* ignore backup errors */
    }
    await fs.writeFile(config.aliceConfigPath, conf, 'utf-8');
    const { stdout, stderr } = await execAsync(config.aliceReloadCmd, { timeout: 20000 });

    await logAudit({ actor: req.user?.email, action: 'routeserver.apply', resource: 'AliceLG', after: { servers: servers.length } });
    res.json({ success: true, data: { applied: true, output: (stdout || stderr || '').slice(0, 500) } });
  } catch (error: any) {
    console.error('Apply alice config error:', error);
    res.status(500).json({ success: false, error: `Failed to apply: ${error?.message || 'unknown error'}` });
  }
};

export default {
  listRouteServers,
  createRouteServer,
  updateRouteServer,
  deleteRouteServer,
  previewConfig,
  applyConfig,
};
